sudo: false
language:
  - ruby
  - java
rvm:
  - 2.1.6
jdk:
  - oraclejdk8
branches:
  only:
      - master
services:
  - redis-server
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:seed
  - bundle exec rake db:seed RAILS_ENV=test
  - bundle exec rake solr:start
  - bundle exec rake solr:build

