version: '2'
services:
  app:
    build: .
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/app
    depends_on:
      - solr
      - mysql
      - redis
  solr:
    image: gnames/solr:latest
  mysql:
    image: mysql:5.6
    volumes:
      mysql:/var/lib/mysql
volumes:
  mysql;
    external: false

