---
apiVersion: v1
kind: Service
metadata:
  name: resolver
  namespace: gn
  labels:
    app: resolver
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: resolver
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resolver
  namespace: gn
spec:
  replicas: 1
  template:
    metadata:
      namespace: gn
      name: resolver
      labels:
        app: resolver
        tier: frontend
    spec:
      volumes:
        - name: app-vol
          emptyDir: {}
      containers:
        - name: resolver
          image: gnames/resolver:2017-07-18-1e45727

          env:
            - name: RAILS_ENV
              value: production
            - name: GNI_UNICORN_WORKER_PROCESSES
              valueFrom:
                configMapKeyRef:
                  name: resolver
                  key: unicorn.workers
            - name: GNI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: resolver
                  key: server.url
            - name: GNI_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: resolver
                  key: db
            - name: GNI_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: resolver
                  key: db.database
            - name: GNI_SOLR_URL
              valueFrom:
                configMapKeyRef:
                  name: resolver
                  key: solr.url
            - name: GNI_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: resolver
                  key: db.user
            - name: GNI_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resolver
                  key: db.user.password
          ports:
            - containerPort: 8080
              name: unicorn
          command:
            - /app/exe/unicorn-start
          volumeMounts:
            - name: app-vol
              mountPath: /var/www

        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis

        - name: nginx
          image: nginx
          livenessProbe:
            httpGet:
              path: /name_resolvers.json?names=Plantago+major&data_source_ids=1
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /name_resolvers.json?names=Plantago+major&data_source_ids=1
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 3
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: app-vol
              mountPath: /var/www
          command:
            - bash
            - -c
            - "sleep 4 && var/www/app/exe/nginx-start"
